export const CHANGE_DATA = 'CHANGE_DATA';

export const SET_FORM_DATA = 'SET_FORM_DATA';

export const SET_LABEL_FILE = 'SET_LABEL_FILE';

export const SET_PRIMARY_NOTES = 'SET_PRIMARY_NOTES';

export const SET_HINT_NOTES = 'SET_HINT_NOTES';

export const SET_GLASSWARES = 'SET_GLASSWARES';